# Site settings
title: Dominik Boller - Software Engineer
description: A blog about lorem ipsum dolor sit amet
baseurl: ""
url: "https://boller.site"

# User settings
username: Dominik Boller
user_description: I love all things coding and I have a genuine passion for software engineering.
user_title: Full Stack Software Engineer
email: boller.dominik@gmail.com
twitter_username: lorem_ipsum
github_username:  bollerdominik
gplus_username:  lorem_ipsums

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
